price_picker/models/__init__.py
from .user import User
from .device import Device, Manufacturer, Repair, Picture, Color
from .feedback import Feedback
from .preferences import Preferences, Encryption
from .enquiry import Enquiry
from .shop import Shop
from .mail import Mail
from .coupon_code import CouponCode

__all__ = [
    'User',
    'Device',
    'Manufacturer',
    'Feedback',
    'Repair',
    'Picture',
    'Color',
    'Preferences',
    'Enquiry',
    'Encryption',
    'Shop',
    'Mail',
    'CouponCode'
]

price_picker/models/coupon_code.py
from price_picker import db
from price_picker.common.database import CRUDMixin


class CouponCode(CRUDMixin, db.Model):
    VALUES = [5, 10]

    __tablename__ = 'coupons'
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(10), unique=True, nullable=False)
    value = db.Column(db.Integer)

    def __repr__(self):
        return "<Coupon %s>" % self.mail

price_picker/models/enquiry.py
from price_picker import db
import datetime as dt
from sqlalchemy.orm import relationship
from price_picker.common.database import CRUDMixin

repairs = db.Table('repairs',
                   db.Column('repair_id', db.Integer, db.ForeignKey('repair.id', ondelete="cascade")),
                   db.Column('enquiry_id', db.Integer, db.ForeignKey('enquiries.id', ondelete="cascade"))
                   )


class Enquiry(db.Model, CRUDMixin):
    __tablename__ = "enquiries"
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=dt.datetime.now)
    name = db.Column(db.String(128))
    customer_first_name = db.Column(db.String(128))
    customer_last_name = db.Column(db.String(128))
    customer_email = db.Column(db.String(128))
    customer_phone = db.Column(db.String(128))
    customer_street = db.Column(db.String(128))
    customer_city = db.Column(db.String(128))
    customer_postal_code = db.Column(db.String(32))
    sale = db.Column(db.Integer, default=0)
    imei = db.Column(db.String(64))
    color = db.Column(db.String(64))
    shop = db.Column(db.String(128))
    device_id = db.Column(db.Integer, db.ForeignKey('devices.id'))
    device = relationship("Device", back_populates="enquiries")
    repairs = relationship("Repair", secondary=repairs)
    done = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f"<Enquiry ({self.name}) from {self.timestamp.strftime('%d.%m.%Y at %H:%M')}>"

    @property
    def address(self):
        return f"{self.customer_street or '-'}, {self.customer_postal_code or '-'}, {self.customer_street or '-'}"

price_picker/__init__.py
import os
import sentry_sdk
import datetime as dt
from flask import Flask, render_template
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from price_picker.common.next_page import next_page
from price_picker.common.url_for_other_page import url_for_other_page
from config import configs
from flask_bootstrap import Bootstrap
from flask_talisman import Talisman
from flask_wtf.csrf import CSRFProtect
from price_picker.analytics import Analytics
from celery import Celery
from redis import Redis
from sentry_sdk.integrations.flask import FlaskIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

# instantiate the extensions
login_manager = LoginManager()
db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
csrf = CSRFProtect()
celery = Celery()
talisman = Talisman()
analytics = Analytics()
r = Redis()


def create_app(config=None, script_info=None):
    # instantiate the app
    app = Flask(
        __name__,
        template_folder="templates",
        static_folder="../assets/static",
        instance_relative_config=True
    )
    conf = os.getenv("APP_CONFIG", "DEFAULT")
    config = config or configs[conf]
    app.config.from_object(config)

    init_talisman(app)
    init_extensions(app)
    register_blueprints(app)
    init_flask_login(app)
    register_error_handlers(app)
    add_jinja_vars(app)
    init_celery(app)
    init_sentry(app)

    # shell context for flask cli
    @app.shell_context_processor
    def ctx():
        from price_picker.models import User, Device, Repair, Manufacturer
        return {"app": app, "db": db, 'User': User, 'Repair': Repair, 'Manufacturer': Manufacturer, 'Device': Device}

    return app


def register_error_handlers(app):
    """ Register custom Error Handlers here """

    @app.errorhandler(401)
    def unauthorized_page(error):
        return render_template("errors/401.html"), 401

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/500.html"), 500


def init_flask_login(app):
    """ Flask Login Setup """

    from price_picker.models import User
    login_manager.login_view = "main.login"
    login_manager.login_message_category = "danger"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == int(user_id)).first()


def init_talisman(app):
    csp = {
        'default-src': [
            '\'self\''
        ],
        'style-src': [
            '\'self\'',
            'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
        ],
        'script-src': [
            '\'self\'',
            'https://d3js.org/d3.v3.min.js',
            'https://code.jquery.com/jquery-3.4.1.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js',
            'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'
        ]
    }
    talisman.init_app(app,
                      content_security_policy=csp,
                      content_security_policy_nonce_in=['script-src'])


def register_blueprints(app):
    """ Register all Blueprints here """
    from price_picker.views.main.views import main_blueprint
    from price_picker.views.admin.views import admin_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(admin_blueprint)


def init_extensions(app):
    """ Register all Extensions here """

    login_manager.init_app(app)
    db.init_app(app)
    bootstrap.init_app(app)
    migrate.init_app(app, db)
    csrf.init_app(app)
    analytics.init_app(app, blueprints=['main', ], redis_url=app.config['REDIS_URL'])
    r = Redis.from_url(app.config['REDIS_URL'])


def add_jinja_vars(app):
    def unix2date(value, format='%H:%M / %d-%m-%Y'):
        """
        convert a unix timestamp to datetime
        """
        try:
            return dt.datetime.utcfromtimestamp(value).strftime(format)
        except Exception:
            pass

    app.jinja_env.filters['unix2date'] = unix2date
    app.jinja_env.globals['url_for_other_page'] = url_for_other_page


def init_sentry(app):
    if 'DSN' in app.config.keys():
        sentry_sdk.init(
            dsn=app.config['DSN'],
            integrations=[FlaskIntegration(), CeleryIntegration()]
        )


def init_celery(app=None):
    app = app or create_app()
    celery.conf.broker_url = app.config['CELERY_BROKER_URL']
    celery.conf.result_backend = app.config['CELERY_RESULT_BACKEND']
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        """Make celery tasks work with Flask app context"""

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery

price_picker/views/admin/views.py
import datetime as dt
import io
import csv

from sqlalchemy import desc
from flask import (
    Blueprint,
    redirect,
    url_for,
    flash,
    request,
    render_template,
    current_app,
    jsonify,
    make_response
)
from flask_login import (
    current_user,
    logout_user
)

from price_picker.models import (
    Device,
    Manufacturer,
    Repair,
    Color,
    Preferences,
    Enquiry,
    Shop,
    Mail
)
from price_picker import (
    db,
    analytics
)
from price_picker.common.next_page import next_page
from price_picker.tasks.mail import TestEmail, send_email_task
from price_picker.common.csv_import import RepairCsvImporter

from .forms import (
    NewDeviceForm,
    EditDeviceForm,
    NewManufacturerForm,
    EditManufacturerForm,
    NewRepairForm,
    NewColorForm,
    ContactSettingsForm,
    MailSettingsForm,
    ChangePasswordForm,
    CsvUploadForm,
    SaleForm,
    EmailTestForm,
    AddShopForm
)

admin_blueprint = Blueprint("admin", __name__, url_prefix="/admin")


@admin_blueprint.before_request
def require_login():
    if not current_user.is_authenticated:
        flash('Dieser Bereich erfordert einen Login!', 'danger')
        return redirect(url_for('main.login', next=request.full_path))


# MANUFACTURERS


@admin_blueprint.route('/manufacturer/add', methods=['GET', 'POST'])
def add_manufacturer():
    form = NewManufacturerForm()
    if form.validate_on_submit():
        m = Manufacturer.create(name=form.name.data, picture=form.picture.data)
        flash(f"{m.name} erfolgreich hinzugefügt", "success")
        return redirect(next_page())
    return render_template('admin/manufacturer.html', form=form)


@admin_blueprint.route('/manufacturer/<int:manufacturer_id>/delete', methods=['POST'])
def delete_manufacturer(manufacturer_id):
    m = Manufacturer.query.get_or_404(manufacturer_id).delete()
    flash(f"{m.name} erfolgreich gelöscht", "success")
    return jsonify(status='ok'), 201


@admin_blueprint.route('/manufacturer/<int:manufacturer_id>/edit', methods=['GET', 'POST'])
def edit_manufacturer(manufacturer_id):
    m = Manufacturer.query.get_or_404(manufacturer_id)
    form = EditManufacturerForm(obj=m)
    if form.validate_on_submit():
        if Manufacturer.query.filter(Manufacturer.id != m.id, Manufacturer.name == form.name.data).first() is not None:
            form.name.errors.append("Es gibt bereits ein Hersteller mit diesem Namen")
            return render_template('admin/manufacturer.html', form=form)
        m.name = form.name.data
        m.picture = form.picture.data
        m.save()
        flash(f"{m.name} erfolgreich aktualisiert", "success")
        return redirect(url_for('main.home'))
    return render_template('admin/manufacturer.html', form=form)


# DEVICES


@admin_blueprint.route('/device/add', methods=['GET', 'POST'])
def add_device():
    m = request.args.get('manufacturer_id', None, int)
    form = NewDeviceForm()
    if form.validate_on_submit():
        d = Device().create(name=form.name.data, manufacturer=form.manufacturer.data, picture=form.picture.data,
                            colors=form.colors.data)
        flash("Gerät erfolgreich hinzugefügt", "success")
        return redirect(url_for('main.select_device', manufacturer_id=d.manufacturer_id))
    if m is not None:
        m = Manufacturer.query.get_or_404(m)
        form.manufacturer.data = m
    return render_template('admin/device.html', form=form)


@admin_blueprint.route('/device/<int:device_id>/delete', methods=['POST'])
def delete_device(device_id):
    d = Device.query.get_or_404(device_id).delete()
    flash(f"{d.name} erfolgreich gelöscht", "success")
    return jsonify(status='ok'), 201


@admin_blueprint.route('/device/<int:device_id>/edit', methods=['GET', 'POST'])
def edit_device(device_id):
    d = Device.query.get_or_404(device_id)
    form = EditDeviceForm(obj=d)
    if form.validate_on_submit():
        if Device.query.filter(Device.id != d.id, Device.name == form.name.data).first() is not None:
            form.name.errors.append("Es gibt bereits ein Gerät mit diesem Namen")
            return render_template('admin/device.html', form=form)
        d.name = form.name.data
        d.manufacturer = form.manufacturer.data
        d.picture = form.picture.data
        d.colors = form.colors.data
        d.save()
        flash(f"{d.name} erfolgreich aktualisiert", "success")
        return redirect(url_for('main.select_device', manufacturer_id=d.manufacturer_id))
    form.colors.data = d.colors
    return render_template('admin/device.html', form=form, manufacturer_id=d.manufacturer_id)


# REPAIRS

@admin_blueprint.route('/device/<int:device_id>/repair/add', methods=['GET'])
def add_repair(device_id):
    device = Device.query.get_or_404(device_id)
    device.repairs.append(Repair())
    db.session.commit()
    flash(f"Neue Reparatur zu {device.name} hinzugefügt", "success")
    return jsonify(status='ok'), 201


@admin_blueprint.route('/repair/<int:repair_id>/edit', methods=['GET', 'POST'])
def edit_repair(repair_id):
    r = Repair.query.get_or_404(repair_id)
    form = NewRepairForm(obj=r)
    if form.validate_on_submit():
        form.populate_obj(r)
        db.session.commit()
        flash(f"{r.name} wurde aktualisiert", "success")
        return jsonify(status='ok'), 201
    return render_template('admin/repair.html', form=form, repair_id=repair_id)


@admin_blueprint.route('/repair/<int:repair_id>/delete', methods=['POST'])
def delete_repair(repair_id):
    r = Repair.query.get_or_404(repair_id).delete()
    flash(f"{r.name} erfolgreich gelöscht", "success")
    return jsonify(status='ok'), 201


# COLORS


@admin_blueprint.route('/color/add', methods=['GET', 'POST'])
def add_color():
    form = NewColorForm()
    if form.validate_on_submit():
        c = Color.create(name=form.name.data, color_code=form.color_code.data)
        flash(f"{c.name} erfolgreich hinzugefügt", "success")
        return redirect(next_page())
    return render_template('admin/color.html', form=form)


@admin_blueprint.route('/color/<int:color_id>/delete', methods=['POST'])
def delete_color(color_id):
    pass


# SHOPS


@admin_blueprint.route('/shop/add', methods=['GET', 'POST'])
def add_shop():
    form = AddShopForm()
    if form.validate_on_submit():
        s = Shop.create(name=form.name.data)
        flash(f"{s.name} erfolgreich hinzugefügt", "success")
        return redirect(url_for('.add_shop'))
    return render_template('admin/panel/shops.html', form=form, shops=Shop.query.all())


@admin_blueprint.route('/shop/<string:shop_id>/delete', methods=['POST'])
def delete_shop(shop_id):
    s = Shop.query.get_or_404(shop_id).delete()
    flash(f"{s.name} erfolgreich gelöscht", "success")
    return jsonify(status='ok'), 201


# SETTINGS


@admin_blueprint.route('/settings/dashboard', methods=['GET', 'POST'])
def dashboard():
    page = request.args.get('page', 1, int)
    query = Enquiry.query.order_by(Enquiry.timestamp.desc())
    pagination = query.paginate(page, per_page=10, error_out=False)
    return render_template('admin/panel/dashboard.html',
                           sub_title="Dashboard",
                           pagination=pagination)


@admin_blueprint.route('/enquiry/<int:enquiry_id>/complete', methods=['POST'])
def complete_enquiry(enquiry_id):
    enquiry = Enquiry.query.get_or_404(enquiry_id)
    enquiry.done = True
    enquiry.save()
    flash("Anfrage erfolgreich abgeschlossen.", 'success')
    return '', 200


@admin_blueprint.route('/settings/contactform', methods=['GET', 'POST'])
def contact_form_settings():
    p = Preferences.query.first()
    if p is None:
        Preferences.create()
        current_app.logger.warning('Missing preferences. Inserting default')

    form = ContactSettingsForm(obj=p)
    if form.validate_on_submit():
        form.populate_obj(p)
        db.session.commit()
        Preferences.load_settings()
        flash('Einstellungen erfolgreich angepasst', 'success')
        return redirect(url_for('.contact_form_settings'))
    return render_template('admin/panel/contactform.html',
                           form=form,
                           sub_title="Kontaktdaten")


@admin_blueprint.route('/settings/mail', methods=['GET', 'POST'])
def mail_settings():
    p = Preferences.query.first()
    if p is None:
        Preferences.create()
        current_app.logger.warning('Missing preferences. Inserting default')

    # Only the email form is validated in this function
    # The Test Form is validated in a separate function
    email_form = MailSettingsForm(obj=p)
    email_test_form = EmailTestForm()
    if email_form.validate_on_submit():
        p.mail_port = email_form.mail_port.data
        p.mail_server = email_form.mail_server.data
        p.mail_default_sender = email_form.mail_default_sender.data
        p.mail_encryption = email_form.mail_encryption.data
        p.mail_username = email_form.mail_username.data
        p.order_copy_mail_address = email_form.order_copy_mail_address.data
        if email_form.mail_password.data and len(email_form.mail_password.data) > 0:
            p.encrypt_mail_password(email_form.mail_password.data)
        p.save()
        flash('Einstellungen erfolgreich angepasst', 'success')
        return redirect(url_for('.mail_settings'))
    return render_template('admin/panel/mailsettings.html',
                           form=email_form,
                           sub_title="Mail Einstellungen",
                           email_test_form=email_test_form)


@admin_blueprint.route('/settings/password', methods=['GET', 'POST'])
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.password.data
        current_user.save()
        flash('Passwort erfolgreich geändert.', 'success')
        logout_user()
        return redirect(url_for('main.home'))
    return render_template('admin/panel/password.html',

price_picker/templates/main/_base.html
{% extends "_base.html" %}
{% from "_macros.html" import render_stepper %}
{% block title %} - {{ sub_title }}{% endblock %}
{% if not step_count %}{% set step_count = 1 %}{% endif %}
{% block content %}
    {{ render_stepper(step_count) }}
    {% block sub_page %}{% endblock %}
{% endblock %}

price_picker/templates/main/choose_color.html
{% extends "main/_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_macros.html" import render_color with context %}
{% set step_count = 2 %}
{% set sub_title = "Farbauswahl" %}
{% block sub_page %}
    <div class="row justify-content-md-center">
        {% for color in device.colors %}
            {{ render_color(color) }}
        {% endfor %}
    </div>
    <br>
    <a class="btn btn-secondary" href="{{ url_for('main.select_device', manufacturer_id=device.manufacturer.id) }}">&laquo;
        Zurück</a>
{% endblock %}

{% block js %}
    <script nonce="{{ csp_nonce() }}">
        $(document).ready(function () {

            $('.selectable').click(function () {
                sessionStorage.setItem('color', $(this).data('name'));
                window.location.href = '{{ url_for("main.select_repair", device_id=device.id) }}'
            });

            $('.circle').each(function (i, obj) {
                obj.style.backgroundColor = obj.dataset.color;
            });

        });
    </script>
{% endblock %}

price_picker/templates/main/complete.html
{% extends 'main/_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_macros.html" import warn_message, render_formgroup %}
{% set step_count = 5 %}
{% set sub_title = "Auftragsdaten" %}
{% block sub_page %}
        <div class="col-lg-8 col-sm-8 offset-lg-2">
            <h2 class="text-center">Persönliche Daten</h2>
            <hr>
            <form class="form" role="form" method="post" action="">
                {{ form.hidden_tag() }}
                {{ warn_message(form) }}
                {{ render_formgroup(form.first_name) }}
                {{ render_formgroup(form.last_name) }}
                {{ render_formgroup(form.email) }}
                {{ render_formgroup(form.phone, placeholder="+49") }}
                {% if form.__class__.__name__ == 'AddressContactForm' %}
                    {{ render_formgroup(form.customer_street) }}
                    {{ render_formgroup(form.customer_postal_code) }}
                    {{ render_formgroup(form.customer_city) }}
                {% endif %}
                {{ render_formgroup(form.shop) }}
                <h4 class="text-muted">Gerätedaten</h4>
                {{ render_formgroup(form.imei) }}
                {{ render_formgroup(form.coupon, id="coupon") }}
                {{ form.confirm(class="btn btn-block btn-success") }}
            </form>
            <br>
            <p class="text-center text-muted"><b>&#x2139;</b> Die abgesendeten Daten werden nur zum Zweck der
                Bearbeitung Ihres Anliegens
                verarbeitet.
                Weitere Informationen finden Sie in unserer <a target="_blank" rel="noopener noreferrer"
                                                               href="https://www.smartphoniker.de/datenschutz/">Datenschutzerklärung</a>.
            </p>
        </div>
        <a class="btn btn-secondary" href="{{ url_for('main.select_repair', device_id=device_id) }}">&laquo; Zurück</a>
{% endblock %}

{% block js %}
    <script nonce="{{ csp_nonce() }}">
        function isValid(obj, bool) {
            if (bool) {
                $(obj).addClass("is-valid").removeClass('is-invalid');
            } else {
                $(obj).addClass("is-invalid").removeClass('is-valid');
            }
        }

        function verifyCode(code) {
            var url = "{{ url_for('main.verify_code') }}";
            $.ajax({
                url: url,
                type: "POST",
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                data: JSON.stringify({'code': code}),
                success: function (result) {
                    isValid('#coupon', true);
                },
                error: function (xhr, resp, text) {
                    isValid('#coupon', false);
                }
            });
        }

        $('#coupon').keyup(delay(function () {
                var v = $(this).val();
                if (v.length >= 1) {
                    verifyCode(v);
                } else {
                    $(this).removeClass('is-valid').removeClass('is-invalid');
                }
            }, 500)
        ).keyup();
    </script>
{% endblock %}

price_picker/templates/main/home.html
{% extends "_base.html" %}
{% from "_macros.html" import render_manufacturer with context %}
{% block page_title %}- Herstellerauswahl{% endblock %}
{% block content %}
    <h1 class="text-center">Wie lautet der Hersteller?</h1>
    <br>

    <div class="row">
        {% for manufacturer in manufacturers %}
            {{ render_manufacturer(manufacturer) }}
        {% endfor %}

        {% if current_user.is_authenticated %}
            <!-- Always include an add option if admin is logged in-->
            <div class="col-sm-4 py-2 text-center">
                <a href="{{ url_for('admin.add_manufacturer') }}"
                   class="stretched-link"></a>
                <div class="card bg-primary h-100">
                    <div class="card-body text-white align-items-center d-flex justify-content-center">
                        <h1>Neu</h1>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    {% if current_user.is_authenticated %}
        <!-- Delete Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
             aria-hidden="true">
            <div class="modal-dialog text-center" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Bist du sicher?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Soll der Hersteller wirklich entfernt werden? Alle Geräten werden dann ebenfalls
                            gelöscht!</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
                        <button class="btn btn-danger" id="deleteConfirmBtn">Ja</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block js %}
    <script nonce="{{ csp_nonce() }}">
        $(document).ready(function () {

            $('.deleteBtn').click(function () {
                $('#deleteConfirmBtn').data('action', $(this).data('action'));
            });

            $('#deleteConfirmBtn').click(function () {
                $.post($(this).data('action')).done(function () {
                    location.reload();
                });
            });

            $('.manufacturer').click(function () {
                window.location.href = $(this).data('url');
            });
        });
    </script>
{% endblock %}

price_picker/templates/main/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_macros.html" import warn_message, render_field %}
{% block content %}

    <header class="content-header">
        <h1>Login</h1>
        <hr>
    </header>
    <br>
    <form class="form" role="form" method="post" action="">
        {{ form.hidden_tag() }}
        {{ warn_message(form) }}
        <div class="col-lg-4 col-sm-4">
            {{ render_field(form.username) }}
            {{ render_field(form.password) }}
            {{ wtf.form_field(form.remember_me) }}
            <button class="btn btn-success" type="submit">Anmelden</button>
        </div>
    </form>

{% endblock %}

price_picker/templates/main/select_device.html
{% extends "main/_base.html" %}
{% from "_macros.html" import render_device with context %}
{% set step_count = 1 %}
{% set sub_title = "Geräteauswahl" %}
{% block sub_page %}
        <div class="row">
            {% for device in devices %}
                {{ render_device(device) }}
            {% endfor %}

            {% if current_user.is_authenticated %}
                <!-- Always include an add option if admin is logged in-->
                <div class="col-sm-4 py-2 text-center">
                    <a href="{{ url_for('admin.add_device', manufacturer_id=manufacturer_id) }}"
                       class="stretched-link"></a>
                    <div class="card bg-primary h-100">
                        <div class="card-body text-white align-items-center d-flex justify-content-center">
                            <h1>Neu</h1>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        <br>
        <a class="btn btn-secondary" href="{{ url_for('main.home') }}">&laquo; Zurück</a>
    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog text-center" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Bist du sicher?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Soll das Gerät wirklich entfernt werden?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
                    <button class="btn btn-danger" id="deleteConfirmBtn">Ja</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script nonce="{{ csp_nonce() }}">
        $(document).ready(function () {

            $('.deleteBtn').click(function () {
                $('#deleteConfirmBtn').data('action', $(this).data('action'));
            });

            $('#deleteConfirmBtn').click(function () {
                $.post($(this).data('action')).done(function () {
                    location.reload();
                });
            });

              $('.device').click(function () {
                window.location.href = $(this).data('url');
            });

        });

    </script>
{% endblock %}

price_picker/templates/main/thank_you.html
{% extends "_base.html" %}
{% block content %}
    <div class="jumbotron">
        <div class="text-center">
            <h1>Vielen Dank!</h1>
            <p>
                Wir haben Ihre Anfrage erhalten und werden diese schnellst möglich bearbeiten.
                Ein Mitarbeiter wird Ihre Anfrage abschließend prüfen und sich bei Ihnen melden.
                Bei dringlichen Fragen erreichen Sie uns während unserer Öffnungszeiten.
                Die Kontaktdaten entnehmen Sie unserer
                <a {% if config['HOMEPAGE'] %}href="{{ config['HOMEPAGE'] }}" {% endif %}>Homepage</a>.
            </p>
            <a class="btn btn-primary" href="{{ url_for(request.args.get('next') or 'main.home') }}">Weiter</a>
        </div>
    </div>

{% endblock %}